version: "3"

services:
  kamailio:
    image: kamailio-dev-dc:master
    build:
      context: .
      dockerfile: Dockerfile.kamailio
    volumes:
      - ./kamailio:/etc/kamailio
      - ./db:/db
    ports:
      - "5060:5060"
      - "udp/5060:5060"
    networks:
      main:
        aliases:
          - kamailio

  asterisk:
    image: asterisk-dev-dc:master
    build:
      context: .
      dockerfile: Dockerfile.asterisk
    networks:
      main:
        aliases:
          - asterisk
    volumes:
      - ./asterisk:/etc/asterisk

networks:
  main: