version: "3"

services:
  kamailio:
    image: kamailio:redirect-302
    build:
      context: .
      dockerfile: Dockerfile.kamailio
    volumes:
      - "./kamailio:/etc/kamailio"
    ports:
      - "5060:5060/udp"
    #  - "5060:5060/tcp"
      - "8080:80/tcp"
    #extra_hosts:
    #  - "sip.localhost.com:127.0.0.1"
    networks:
      main:
        aliases:
          - kamailio
    #depends_on:
    #  - db
  
  asterisk_1:
    image: asterisk:redirect-302
    build:
      context: .
      dockerfile: Dockerfile.asterisk
    ports:
      - "5061:5061/udp"
      - "5061:5061/tcp"
    networks:
      main:
        aliases:
          - asterisk_1
    volumes:
      - "./asterisk_1:/etc/asterisk"

  asterisk_2:
    image: asterisk:redirect-302
    build:
      context: .
      dockerfile: Dockerfile.asterisk
    ports:
      - "5062:5062/udp"
      - "5062:5062/tcp"
    networks:
      main:
        aliases:
          - asterisk_2
    volumes:
      - "./asterisk_2:/etc/asterisk"

  #db:
  #  image: mariadb
  #  environment:
  #    MYSQL_DATABASE: 'kamailio'
  #    MYSQL_USER: 'kamailio'
  #    MYSQL_PASSWORD: 'kamailiorw'
  #    MYSQL_ROOT_PASSWORD: 'dbrootpw'
  #  networks:
  #    main:
  #      aliases:
  #        - db
networks:
  main: