version: "3"

services:
  kamailio:
    image: kamailio:sms_receive
    build:
      context: .
      dockerfile: Dockerfile.kamailio
    volumes:
      - ./kamailio:/etc/kamailio
    networks:
      main:
        aliases:
          - kamailio
    depends_on:
      - sipp
  
  sipp:
    image: sipp:sms_receive
    build:
      context: .
      dockerfile: Dockerfile.sipp
    volumes:
      - ./sipp:/opt
    networks:
      main:
        aliases:
          - sipp

networks:
  main: