version: "3"

services:
  kamailio:
    image: kamailio:test
    build:
      context: .
      dockerfile: Dockerfile.kamailio
    volumes:
      - ./kamailio:/etc/kamailio
    ports:
      - "5060:5060/udp"
    networks:
      main:
        aliases:
          - kamailio
    depends_on:
      - db
  
  asterisk:
    image: asterisk:test
    build:
      context: .
      dockerfile: Dockerfile.asterisk
    networks:
      main:
        aliases:
          - asterisk
    volumes:
      - ./asterisk:/etc/asterisk

  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: 'kamailio'
      MYSQL_USER: 'kamailio'
      MYSQL_PASSWORD: 'kamailiorw'
      MYSQL_ROOT_PASSWORD: 'dbrootpw'
    networks:
      main:
        aliases:
          - db
networks:
  main: