version: "3"

services:
  kamailio:
    image: kamailio:test
    build:
      context: .
      dockerfile: Dockerfile.kamailio
    volumes:
      - "./kamailio:/etc/kamailio"
    ports:
      - "5080:5080/udp"
      - "5080:5080/tcp"
    extra_hosts:
      - "sip.localhost.com:127.0.0.1"
    networks:
      main:
        aliases:
          - kamailio
    depends_on:
      - db
  
  asterisk_1:
    image: asterisk:test
    build:
      context: .
      dockerfile: Dockerfile.asterisk
    networks:
      main:
        aliases:
          - asterisk_1
    volumes:
      - "./asterisk_1:/etc/asterisk"

  asterisk_2:
    image: asterisk:test
    build:
      context: .
      dockerfile: Dockerfile.asterisk
    networks:
      main:
        aliases:
          - asterisk_2
    volumes:
      - "./asterisk_2:/etc/asterisk"

  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: 'kamailio'
      MYSQL_USER: 'kamailio'
      MYSQL_PASSWORD: 'kamailiorw'
      MYSQL_ROOT_PASSWORD: 'dbrootpw'
    networks:
      main:
        aliases:
          - db
networks:
  main: