version: "3"

services:
  kamailio:
    image: kamailio:test
    user: "1000:100"
    build:
      context: .
      dockerfile: Dockerfile.kamailio
    volumes:
      - ./kamailio:/etc/kamailio
    ports:
      - "5060:5060"
      - "5061:5061"
    networks:
      main:
        aliases:
          - kamailio
    depends_on:
      - rtpengine

  rtpengine:
    image: rtpengine:latest
    user: "1000:100"
    build:
      context: .
      dockerfile: Dockerfile.rtpengine
    networks:
      main:
        aliases:
          - db
networks:
  main: