version: "3"

services:
  kamailio:
    image: kamailio-dev-dc:kwc2020-lb
    build:
      context: .
      dockerfile: Dockerfile.kamailio
    volumes:
      - ./kamailio:/etc/kamailio
      - ./db:/db
    ports:
      - "5060:5060"
      - "5060:5060/udp"
    extra_hosts:
      - "sip.localhost.com:127.0.0.1"
    networks:
      main:
        aliases:
          - kamailio

  asterisk_1:
    image: asterisk-dev-dc:kwc2020-lb
    build:
      context: .
      dockerfile: Dockerfile.asterisk
    networks:
      main:
        aliases:
          - asterisk_1
    volumes:
      - "./asterisk_1:/etc/asterisk"

  asterisk_2:
    image: asterisk-dev-dc:kwc2020-lb
    build:
      context: .
      dockerfile: Dockerfile.asterisk
    networks:
      main:
        aliases:
          - asterisk_2
    volumes:
      - "./asterisk_2:/etc/asterisk"

networks:
  main: