version: "3"

services:
  kamailio:
    image: kamailio:test
    build:
      context: .
      dockerfile: Dockerfile.kamailio
    volumes:
      - ./kamailio:/etc/kamailio
    ports:
      - "5060:5060"
      - "5061:5061"
    networks:
      main:
        aliases:
          - kamailio

  rtpengine:
    image: rtpengine:latest
    build:
      context: .
      dockerfile: Dockerfile.rtpengine
    networks:
      main:
        aliases:
          - rtpengine
networks:
  main: